language: python
python:
  - 3.8
branches:
  only:
    - master
notifications:
  email: false

sudo: true
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - gfortran
      - libpulse-mainloop-glib0
      - libopenblas-base

before_install:
  - sudo apt-get update
  - pwd
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm
  #- sudo ln -s -f bash /bin/sh
  - bash continuous-integration/travis/install.sh
  - ls $HOME/Documents/MFA/thirdparty/bin -al

# Install packages
install:
  - export PATH="$HOME/miniconda/miniconda/bin:$PATH"
  - conda activate test-environment
  - which python
  - conda list

# Run test
script:
  #- coverage help
  - travis_wait 120 coverage run --source=montreal_forced_aligner setup.py test

# Calculate coverage
after_success:
  - coveralls

after_failure:
  - ls tests/data/generated/sickcorpus/corpus_data/split2/log
  - cat tests/data/generated/sickcorpus/corpus_data/split2/log/make_mfcc.0.log

cache:
  directories:
    - $HOME/miniconda
    - $HOME/tools
