language: python
python:
  - 3.8
branches:
  only:
    - master
notifications:
  email: false

sudo: true
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - gfortran
      - libpulse-mainloop-glib0
      - libopenblas-base

before_install:
  - sudo apt-get update
  - pwd

# Install packages
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment -c conda-forge python=$TRAVIS_PYTHON_VERSION openfst=1.7.6 pynini=2.1.0 ngram=1.3.9 baumwelch=0.3.1
  - conda activate test-environment
  - pip install -r requirements.txt
  - pip install -q coveralls coverage pytest setuptools
  - which python
  - conda list
  - python -m montreal_forced_aligner.command_line.thirdparty download
  - ls $HOME/Documents/MFA/thirdparty/bin -al
  - bash continuous-integration/travis/install.sh

# Run test
script:
  #- coverage help
  - travis_wait 120 coverage run --source=montreal_forced_aligner setup.py test

# Calculate coverage
after_success:
  - coveralls

after_failure:
  - ls tests/data/generated/sickcorpus/corpus_data/split2/log
  - cat tests/data/generated/sickcorpus/corpus_data/split2/log/make_mfcc.0.log

cache:
  directories:
    - $HOME/tools
